### ISSUE TITLE
Migrate Dependabot to version 2

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#1959]
#### Kullanım senaryosu

[//]: # (Kullanım senaryosunu yaz veya dış bir dokümana bağlantı oluştur)

Recently Dependabot announced version 2, aka [Dependabot native](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates), a new more native-ish version that integrates with the existing security features of Github and the [Security](https://github.com/omu/nokul/security) tab.

- The good: Integrates well with existing Github features and provides upgrades for _GH actions_ flows, which is not possible to achieve with v1.
- The bad: Doesn't support automated merges.
- The ugly: Still in beta and might create some maintenance hassle if config options change radically.

#### Integration

- Remove `.dependabot` folder.
- Create a file named as `dependabot.yml` under the `.github` folder and add your v2 config.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [ ] Özellik ürün takımı tarafından incelendi ve onaylandı
- [ ] İş kaydını "Product" projesiyle ilişkilendirdim
- [ ] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kullanım senaryosuna ilave açıklamalar)
[//]: # (Mockuplar)
[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

A possible replacement:

```yml
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:30"
      timezone: "Europe/Istanbul"
    commit-message:
      prefix: "[rb prod]"
      prefix-development: "[rb dev]"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:30"
      timezone: "Europe/Istanbul"
    commit-message:
      prefix: "[js prod]"
      prefix-development: "[js dev]"
      include: "scope"
```

- https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates
- https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically
