### ISSUE TITLE
AdministrativeUnits verisi primary_key'lere bağımlı

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#330]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

`administrative_units.yml`'da şöyle satırlar var:

```
15086663:
  parent_yoksis_id: 174829
  detsis_id: 15086663
  name: ADALET MESLEK YÜKSEKOKULU MÜDÜRLÜĞÜ
  district_id: 756
  unit_status_id: 2
10190983:
  parent_yoksis_id: 174829
  detsis_id: 10190983
  name: ADALET HUKUK BÖLÜM BAŞKANLIĞI
  district_id: 756
  unit_status_id: 2
```

Bu aşırı tehlikeli bir davranış çünkü kayıtlar primary_key'lere bağımlı. Örneğin yarın 756 ID'li bir district olacağının hiç bir garantisi yok. Daha doğrusu sistemdeki ilk District'in ID'sinin daima 1 olacağı varsayımı baştan yanlış. Ya tüm district'leri destroy edip tekrar oluşturursam?

**Olması gereken davranış:**

[//]: # (Kısa ve net bir şekilde hata yerine olması gereken uygulama davranışının ne olması gerektiğini açıklayınız. Örn: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

Primary ID'lere referans vermek yerine `code` bilgisi kullanılmalı.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) emin misiniz?
