### ISSUE TITLE
Address ve Identity modeli tercümelerinde yanlış attribute key'leri var

### ISSUE THREAD

**Issue by msdundar** [omu/nokul#375]
**Hatayı ve/veya bug'ı açıklayın:**

[//]: # (Kısa ve net bir şekilde hatanın ne olduğu açıklanmalıdır.)

Address ve Identity modelinde name diye bir attribute ve names diye bir enum yok, ancak config/locales'te bunları işaret eden çeviriler var.

```
tr:
  activerecord:
    attributes:
      address: &address_attributes
        **name**: Adres Türü
        phone_number: Cep Telefonu Numarası
        full_address: Açık Adres
        district: İlçe
    enums:
      address:
        **names**:
          formal: Resmi Adres
          informal: Diğer Adres
```

**Olması gereken davranış:**

[//]: # (Kısa ve net bir şekilde hata yerine olması gereken uygulama davranışının ne olması gerektiğini açıklayınız. Örn: X kaydı silindiğinde Z sayfasına yönlendirme yapılmalı.)

Address modelinde `name` diye bir alan olmadığı için bu attribute `names` değil `types` olmalı.

**Katkı sağlama:**

[//]: # (Bu iş kaydının size atanmasını istiyor musunuz* Yardımına/bilgisine ihtiyaç duyduğunuz diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunuzu belirtin.)

* [X] Evet, bu iş kaydının bana atanmasını istiyorum.

**Kontrol listesi:**

* [X] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [X] [Katkı sağlama dokümanını](https://github.com/omu/nokul/CONTRIBUTING.md) okudunuz mu?
* [X] Öneriniz ile alakalı açık olarak bekleyen bir [issue](https://github.com/omu/nokul/issues) veya [pull request](https://github.com/omu/nokul/pulls) emin misiniz?
