### ISSUE TITLE
Birimleri eşleştirecek çözüm üretilmeli

### ISSUE THREAD

**Issue by ekural** [omu/nokul#885]
Birim ağacımızda aynı birimde ders alınmasına karşın farklı burs tiplerine sahip oldukları için farklı yöksis id'ye ve farklı isimlendirmeye sahip birimler var. Uygulamada bu birimlere tekil davranılabilmesi için çözüm üretilmeli. 

Örneğin: 
Beslenme ve Diyetetik Programı - 240429
Beslenme ve Diyetetik Programı (%25 Burslu) - 308558
Beslenme ve Diyetetik Programı (%50 Burslu) - 304711
Bu birim altındaki öğrenciler farklı harç miktarlarına sahip. Ancak aynı sınıfta aynı koşullarda ders alıyorlar ve aynı müfredata tabiler. Sisteme girişleri, ödemeleri ve yöksis haberleşmeleri dışındaki tüm süreçleri tekil takip ediliyor. Bu durum KHK ile üniversitemize gelen öğrenciler ile birlikte gelişti. Muhtemelen mevcut öğrencilerin mezuniyeti ile birlikte ortadan kalkacaktır.

Daha önce birim ağacı ile ilgili düzenlemeler yaparken bu gibi birimlerde kullanmak üzere "effective unit" çözümü konuşulmuştu. Buna göre ilgili birimlere ana birimi gösteren "effective unit" alanı açılacaktı. Konuyla ilgili çözüm önerisi ve çözüm süreci görüşülmeli.

**Comment by roktas** [comment]
`effective_yoksis_id` fikrini ben önermiştim.  Daha somut konuşmak gerekirse, https://github.com/omu/nokul/blob/develop/plugins/tenant/omu/db/units/src/yok.yml dosyasında yukarıdaki örneğe göre burslu programlara `effective_yoksis_id` alanı ekleyerek bu alanı burssuz programın `yoksis_id` numarası olarak atayalım.

```yaml
- name: Beslenme ve Diyetetik Programı
  abbreviation: SAĞLIK-YO-BESLENME-PR
  yoksis_id: '240429'
  parent_yoksis_id: '147574'
  unit_type_id: Önlisans/lisans Programı
  unit_status_id: Yarı Pasif
  district_id: Atakum
  osym: '108210832'
  unit_instruction_language_id: Türkçe
  unit_instruction_type_id: Normal Öğretim
  duration: 4

- name: Beslenme ve Diyetetik Programı (%25 Burslu)
  abbreviation: SAĞLIK-YO-BESLENME-PR-YİRMİBEŞ
  yoksis_id: '308558'
  parent_yoksis_id: '147574'
  effective_yoksis_id: '240429'
  unit_type_id: Önlisans/lisans Programı
  unit_status_id: Yarı Pasif
  district_id: Atakum
  unit_instruction_language_id: Türkçe
  unit_instruction_type_id: Normal Öğretim
  duration: 4

- name: Beslenme ve Diyetetik Programı (%50 Burslu)
  abbreviation: SAĞLIK-YO-BESLENME-PR-ELLİ
  yoksis_id: '304711'
  parent_yoksis_id: '147574'
  effective_yoksis_id: '240429'
  unit_type_id: Önlisans/lisans Programı
  unit_status_id: Yarı Pasif
  district_id: Atakum
  unit_instruction_language_id: Türkçe
  unit_instruction_type_id: Normal Öğretim
duration: 4
```

Program lojiğinde de şöyle yapalım: ilgili süreçlerde (ders alma, müfredat vs) önce `effective_yoksis_id` özelliğine bakalım ve varsa onu kullanalım; yoksa normal `yoksis_id` ile devam edelim.

@omu/backend WDYT?
